// Existing icons (default exports)
export { default as EditIcon } from "./EditIcon";
export { default as DeleteIcon } from "./DeleteIcon";
export { default as LocationIcon } from "./LocationIcon";
export { default as MapIcon } from "./MapIcon";
export { default as JourneyIcon } from "./JourneyIcon";
export { default as ImagePlusIcon } from "./ImagePlusIcon";
export { default as ArrowLeftIcon } from "./ArrowLeftIcon";
export { default as ArrowDownIcon } from "./ArrowDownIcon";
export { default as ArrowUpRightIcon } from "./ArrowUpRightIcon";
export { default as PlaceToStayIcon } from "./PlaceToStayIcon";

// Existing icons (named exports)
export { CalendarIcon } from "./CalendarIcon";
export { BuildingMonumentIcon } from "./BuildingMonumentIcon";
export { TreesIcon } from "./TreesIcon";
export { FoodIcon } from "./FoodIcon";
export { TransportIcon } from "./TransportIcon";
export { NotesIcon } from "./NotesIcon";
export { HeartIcon } from "./HeartIcon";
export { ChatIcon } from "./ChatIcon";

// Phase 1 - High Priority Duplicate Icons
export { CloseIcon } from "./CloseIcon";
export { SearchIcon } from "./SearchIcon";
export { AlertTriangleIcon } from "./AlertTriangleIcon";
export { CheckIcon } from "./CheckIcon";
export { BellIcon } from "./BellIcon";
export { MapFoldedIcon } from "./MapFoldedIcon";
export { ImageUploadIcon } from "./ImageUploadIcon";
export { ChevronRightIcon } from "./ChevronRightIcon";
export { ChevronDownIcon } from "./ChevronDownIcon";
export { ChevronLeftIcon } from "./ChevronLeftIcon";

// Phase 2 - Complex Single-Use Icons
export { GoogleIcon } from "./GoogleIcon";
export { FacebookIcon } from "./FacebookIcon";
export { AppleIcon } from "./AppleIcon";
export { UserProfileIcon } from "./UserProfileIcon";
export { UserCircleIcon } from "./UserCircleIcon";
export { LogoutIcon } from "./LogoutIcon";
export { Box3DIcon } from "./Box3DIcon";
export { PlayIcon } from "./PlayIcon";
export { PauseIcon } from "./PauseIcon";
export { ImagePlaceholderIcon } from "./ImagePlaceholderIcon";
export { PostsEmptyIcon } from "./PostsEmptyIcon";
export { SendIcon } from "./SendIcon";
export { SpinnerIcon } from "./SpinnerIcon";
export { RefreshIcon } from "./RefreshIcon";
export { ErrorCircleIcon } from "./ErrorCircleIcon";
export { ChatBubbleIcon } from "./ChatBubbleIcon";
export { ArrowRightIcon } from "./ArrowRightIcon";
export { ClockIcon } from "./ClockIcon";
export { ClipboardIcon } from "./ClipboardIcon";
export { MailIcon } from "./MailIcon";

// Phase 3 - New Migration Icons (January 2026)
export { GlobeIcon } from "./GlobeIcon";
export { PinIcon } from "./PinIcon";
export { EyeIcon } from "./EyeIcon";
export { EyeOffIcon } from "./EyeOffIcon";
export { KeyIcon } from "./KeyIcon";
export { PhoneIcon } from "./PhoneIcon";
export { LockIcon } from "./LockIcon";
export { ShieldIcon } from "./ShieldIcon";
export { MessageSquareIcon } from "./MessageSquareIcon";
export { UserPlusIcon } from "./UserPlusIcon";
export { HomeIcon } from "./HomeIcon";
export { SettingsIcon } from "./SettingsIcon";
export { InfoIcon } from "./InfoIcon";
export { CopyIcon } from "./CopyIcon";
export { DownloadIcon } from "./DownloadIcon";
export { ShareIcon } from "./ShareIcon";
export { PhotoIcon } from "./PhotoIcon";
export { PlusIcon } from "./PlusIcon";
export { MinusIcon } from "./MinusIcon";
export { VideoIcon } from "./VideoIcon";
export { DotsVerticalIcon } from "./DotsVerticalIcon";
export { TrashIcon } from "./TrashIcon";
export { ExploreIcon } from "./ExploreIcon";
export { ImageIcon } from "./ImageIcon";
export { UploadIcon } from "./UploadIcon";
export { PlayCircleIcon } from "./PlayCircleIcon";
export { LanguageIcon } from "./LanguageIcon";
export { ThemeIcon } from "./ThemeIcon";
export { WarningIcon } from "./WarningIcon";
export { ErrorIcon } from "./ErrorIcon";
export { BanIcon } from "./BanIcon";
export { FileTextIcon } from "./FileTextIcon";
export { HelpCircleIcon } from "./HelpCircleIcon";
export { XIcon } from "./XIcon";
export { AlertCircleIcon } from "./AlertCircleIcon";
export { MapPinIcon } from "./MapPinIcon";
export { RefreshCwIcon } from "./RefreshCwIcon";
export { ChevronUpIcon } from "./ChevronUpIcon";
export { UsersIcon } from "./UsersIcon";
export { SparklesIcon } from "./SparklesIcon";
export { ArrowLeftSimpleIcon } from "./ArrowLeftSimpleIcon";
export { ArrowRightSimpleIcon } from "./ArrowRightSimpleIcon";
export { ArrowUpIcon } from "./ArrowUpIcon";
export { ArrowDownSimpleIcon } from "./ArrowDownSimpleIcon";
export { LightningIcon } from "./LightningIcon";
export { ClipboardListIcon } from "./ClipboardListIcon";
export { CompassIcon } from "./CompassIcon";
export { AirplaneIcon } from "./AirplaneIcon";
export { CameraIcon } from "./CameraIcon";
export { HikingIcon } from "./HikingIcon";
export { TrainIcon } from "./TrainIcon";
export { ShipIcon } from "./ShipIcon";
export { HotAirBalloonIcon } from "./HotAirBalloonIcon";
export { BackpackIcon } from "./BackpackIcon";
export { MountainIcon } from "./MountainIcon";
export { GlobeIllustration } from "./GlobeIllustration";
export { MapRouteIllustration } from "./MapRouteIllustration";
export { SocialNetworkIllustration } from "./SocialNetworkIllustration";
export { FolderDocumentIcon } from "./FolderDocumentIcon";
