export const DISCOVER_MIN_RADIUS_KM = 50;

export const DISCOVER_DEFAULT_RADIUS_KM = 500;

export const DISCOVER_MAX_RADIUS_KM = 1000;

export const DISCOVER_RADIUS_OPTIONS_KM = [
  DISCOVER_MIN_RADIUS_KM,
  100,
  250,
  DISCOVER_DEFAULT_RADIUS_KM,
  DISCOVER_MAX_RADIUS_KM,
] as const;

export const DISCOVER_DEFAULT_LIMIT = 20;
