export const TRIP_COPY = {
  actions: {
    addInboxItem: 'Add to inbox',
    applyProposal: 'Apply selected changes',
    create: 'Create trip',
    createFirst: 'Create your first trip',
    invite: 'Invite traveller',
    open: 'Open workspace',
    publishDraft: 'Generate private draft',
    recalculate: 'Check this plan',
    refresh: 'Refresh trip',
    startLive: 'Start live mode',
    close: 'Close',
    markComplete: 'Mark complete',
    openMapEquivalent: 'Show map equivalent',
    resolve: 'Resolve',
    schedule: 'Schedule',
    skip: 'Skip',
  },
  create: {
    currency: 'Currency',
    dates: 'Travel dates',
    description: 'Give everyone a little context',
    descriptionPlaceholder: 'What kind of trip are you planning?',
    endDate: 'End date',
    flexibleDates: 'Dates are flexible',
    pace: 'Pace',
    startDate: 'Start date',
    timezone: 'Trip timezone',
    title: 'Name this trip',
    titlePlaceholder: 'Late summer in Lisbon',
    travellers: 'Travellers',
    transport: 'Main transport',
  },
  empty: {
    activity: 'Material changes will appear here with who changed what.',
    archived: 'Archived trips stay out of the way until you need them.',
    comments: 'Start a conversation about a day or place.',
    findings: 'No reality checks have been raised for this trip.',
    inbox: 'Save places and Journey selections here before scheduling them.',
    items: 'The day is open. Schedule an inbox item to begin.',
    members: 'Invite an editor or viewer when you are ready to plan together.',
    proposals: 'No suggested changes are waiting for review.',
    trips: 'Turn a place you are curious about into a plan you can actually use.',
  },
  errors: {
    denied: 'You do not have access to this trip.',
    generic: 'This trip could not be loaded.',
    offline: 'You are offline. Saved live details remain available when supported.',
    stale: 'The trip changed after you loaded it. Refresh before applying your changes.',
    validation: 'Check the highlighted fields.',
  },
  findingRules: {
    ANCHOR_CONFLICT: 'Anchored stop conflict',
    INSUFFICIENT_TRANSFER: 'Insufficient transfer time',
    MISSING_LOCATION: 'Missing location',
    TIME_OVERLAP: 'Overlapping times',
  },
  headings: {
    active: 'Active now',
    archived: 'Archived',
    collaboration: 'Collaboration',
    completed: 'Completed',
    ideas: 'Ideas',
    inbox: 'Journey inbox',
    live: 'Live mode',
    overview: 'Overview',
    plan: 'Plan',
    postTrip: 'Post-trip',
    readiness: 'Readiness',
    trips: 'Your trips',
    upcoming: 'Upcoming',
  },
  labels: {
    active: 'Active',
    archived: 'Archived',
    balanced: 'Balanced',
    bicycle: 'Bicycle',
    car: 'Car',
    completed: 'Completed',
    draft: 'Idea',
    editor: 'Editor',
    fast: 'Full days',
    owner: 'Owner',
    planning: 'Planning',
    private: 'Private',
    publicTransit: 'Public transit',
    published: 'Published',
    ready: 'Ready',
    shared: 'Shared',
    slow: 'Unhurried',
    viewer: 'Viewer',
    walk: 'Walking',
    blocking: 'Blocks ready',
    critical: 'Critical',
    high: 'High',
    info: 'Info',
    invited: 'Invited',
    low: 'Low',
    medium: 'Medium',
    open: 'Open',
    resolved: 'Resolved',
    warning: 'Warning',
  },
  list: {
    description: 'Private planning spaces for turning saved ideas into days that hold together.',
    routeNote: 'Every stop, route check and decision stays connected to one itinerary.',
  },
  live: {
    cached: 'Cached for the road',
    description: 'Keep the plan and what actually happened separate.',
    offlineAvailable: 'This snapshot is available without a connection.',
  },
  plan: {
    board: 'Board',
    map: 'Map',
    routeFallback: 'Estimated route',
    timeline: 'Timeline',
    unknownHours: 'Opening hours unknown',
    mapDescription: 'Stops are shown in route order below so the same information is available without a map.',
  },
  postTrip: {
    description: 'Preview exactly what can leave this private workspace.',
    privacyNote: 'Bookings, private notes, attachments, collaborator content, email and precise locations are excluded.',
  },
  sections: {
    actuals: 'Planned and actual',
    comments: 'Comments',
    factors: 'Readiness factors',
    findings: 'Reality findings',
    members: 'Travellers',
    privacyPreview: 'Privacy preview',
    proposals: 'Proposed changes',
    recentActivity: 'Recent activity',
    routeEvidence: 'Route evidence',
    snapshot: 'Offline snapshot',
    source: 'Source and attribution',
  },
  workspace: {
    back: 'All trips',
    destinationsPending: 'Add destinations from the inbox or trip settings.',
    revision: 'Revision',
    role: 'Your access',
  },
  readiness: {
    description: 'A transparent check of timing, routing and unresolved decisions — never a guarantee.',
  },
  status: {
    conflict: 'Changes need review',
    connected: 'Connected',
    loading: 'Loading trip',
    offline: 'Offline',
    saved: 'Saved',
  },
  tabs: {
    collaboration: 'Collaboration',
    inbox: 'Inbox',
    live: 'Live',
    overview: 'Overview',
    plan: 'Plan',
    postTrip: 'Post-trip',
    readiness: 'Readiness',
  },
} as const;
